var EventType = {
    //quill related event types
    QUILL_OPEN: "QUILL_OPEN",
    QUILL_CLOSE: "QUILL_CLOSE",
    QUILL_SELECT_TAB: "QUILL_SELECT_TAB",
    QUILL_CONTENT_CHANGE: "QUILL_CONTENT_CHANGE",
    QUILL_SUBMIT_CHANGE: "QUILL_SUBMIT_CHANGE",
    BLOCK_MOVE_UP:"BLOCK_MOVE_UP",
    BLOCK_MOVE_DOWN:"BLOCK_MOVE_DOWN",

    //block realted event types
    BLOCK_ADD: "BLOCK_ADD",
    BLOCK_DELTE: "BLOCK_DELETE",
    BLOCK_SELECTED: "BLOCK_SELECTED"



};
export default EventType;
